package at.compax.reference.subsystem.fwclogistic.utils;

import java.util.List;
import org.springframework.stereotype.Component;
import at.compax.reference.subsystem.fwclogistic.model.response.FwcOrderQueryResponse;
import at.compax.reference.subsystem.fwclogistic.model.response.FwcOrderResponse;
import at.compax.reference.subsystem.fwclogistic.model.response.FwcOrderResponse.*;

@Component
public class FwcDummyDataGenerator {

  public FwcOrderResponse generateDummyOrderResponse(String referenceNum) {
    CustomerIdentifier customer = CustomerIdentifier.builder()
        .externalId("CUST-001")
        .name("Dummy Customer")
        .id(3L)
        .build();

    Identifier facility = Identifier.builder().name("Main Warehouse").id(2L).build();
    ItemIdentifierResponse itemIdent = ItemIdentifierResponse.builder().sku("SKU-ABC").id(101L).build();

    OrderReadOnly readOnly = OrderReadOnly.builder()
        .orderId(1001L)
        .asnCandidate(2)
        .routeCandidate(3)
        .fullyAllocated(true)
        .importModuleId(1)
        .exportModuleIds("standard-export")
        .deferNotification(false)
        .isClosed(true)
        .processDate("2016-12-25T23:00:00")
        .pickDoneDate("2016-12-25T23:00:00")
        .pickTicketPrintDate("2016-12-25T23:00:00")
        .packDoneDate("2016-12-25T23:00:00")
        .labelsExported(true)
        .invoiceExportedDate("2016-12-25T23:00:00")
        .invoiceDeliveredDate("2016-12-25T23:00:00")
        .loadedState(1)
        .loadOutDoneDate("2016-12-25T23:00:00")
        .reallocatedAfterPickTicketDate("2016-12-25T23:00:00")
        .routeSent(true)
        .asnSentDate("2016-12-25T23:00:00")
        .asnSent(true)
        .pkgsExported(true)
        .batchIdentifier(BatchIdentifier.builder()
            .nameKey(NameKey.builder().customerIdentifier(customer).name("BATCH-01").build())
            .id(1L)
            .build())
        .packages(List.of(Package.builder()
            .packageId(1L)
            .packageTypeId(2)
            .packageDefIdentifier(Identifier.builder().name("Large Box").id(2L).build())
            .length(12.0)
            .width(10.0)
            .height(8.0)
            .weight(2.5)
            .codAmount(0.0)
            .insuredAmount(100.0)
            .trackingNumber("TRK7890123456")
            .description("Standard Shipping Box")
            .createDate("2016-12-25T23:00:00")
            .oversize(false)
            .cod(false)
            .ucc128(1)
            .cartonId("CART-99")
            .label("QA==")
            .packageContents(List.of(PackageContent.builder()
                .packageContentId(1L)
                .packageId(2L)
                .orderItemId(3L)
                .receiveItemId(4L)
                .orderItemPickExceptionId(1L)
                .qty(5.0)
                .lotNumber("LOT123")
                .serialNumber("SN001")
                .expirationDate("2016-12-25T23:00:00")
                .createDate("2016-12-25T23:00:00")
                .serialNumbers(List.of("SN001"))
                .build()))
            .build()))
        .outboundSerialNumbers(List.of(OutboundSerialNumber.builder()
            .itemIdentifier(itemIdent)
            .qualifier("SN")
            .serialNumbers(List.of("SN001"))
            .build()))
        .parcelLabelType(1)
        .customerIdentifier(customer)
        .facilityIdentifier(facility)
        .warehouseTransactionSourceType(7)
        .transactionEntryType(4)
        .importChannelIdentifier(Identifier.builder().name("Shopify").id(2L).build())
        .creationDate("2016-12-25T23:00:00")
        .createdByIdentifier(Identifier.builder().name("API User").id(10L).build())
        .lastModifiedDate("2016-12-25T23:00:00")
        .lastModifiedByIdentifier(Identifier.builder().name("System").id(1L).build())
        .status(1)
        .build();

    ShipToInfo shipTo = ShipToInfo.builder()
        .companyName("Receiver Corp")
        .name("John Doe")
        .address1("123 Delivery Lane")
        .city("Packagetown")
        .state("CA")
        .zip("90210")
        .country("US")
        .emailAddress("john.doe@example.com")
        .build();

    OrderItemResponse orderItem = OrderItemResponse.builder()
        .readOnly(OrderItemReadOnly.builder()
            .orderItemId(101L)
            .fullyAllocated(true)
            .unitIdentifier(Identifier.builder().name("Each").id(1L).build())
            .estimatedQty(1.0)
            .estimatedSecondaryQty(1.0)
            .originalPrimaryQty(1.0)
            .isOrderQtySecondary(true)
            .allocations(List.of(Allocation.builder()
                .receiveItemId(1L)
                .qty(2.0)
                .properlyPickedPrimary(3.0)
                .properlyPickedSecondary(4.0)
                .loadedOut(true)
                .rowVersion("str")
                .detail(AllocationDetail.builder()
                    .itemTraits(ItemTraits.builder()
                        .itemIdentifier(itemIdent)
                        .qualifier("str")
                        .lotNumber("str")
                        .serialNumber("str")
                        .expirationDate("2016-12-25T23:00:00")
                        .palletIdentifier(PalletIdentifier.builder()
                            .nameKey(FacilityNameKey.builder().facilityIdentifier(facility).name("str").build())
                            .id(1L)
                            .build())
                        .build())
                    .locationIdentifier(LocationIdentifier.builder()
                        .nameKey(FacilityNameKey.builder().facilityIdentifier(facility).name("str").build())
                        .id(1L)
                        .build())
                    .savedElements(List.of(SavedElement.builder().name("str").value("str").build()))
                    .build())
                .build()))
            .bin("str")
            .rowVersion("str")
            .build())
        .itemIdentifier(itemIdent)
        .qualifier("str")
        .externalId("str")
        .qty(1.0)
        .secondaryQty(1.0)
        .lotNumber("str")
        .serialNumber("str")
        .expirationDate("2016-12-25T23:00:00")
        .weightImperial(1.0)
        .weightMetric(1.0)
        .notes("str")
        .fulfillInvSalePrice(1.0)
        .fulfillInvDiscountPct(1.0)
        .fulfillInvDiscountAmt(1.0)
        .fulfillInvNote("str")
        .savedElements(List.of(SavedElement.builder().name("str").value("str").build()))
        .proposedAllocations(List.of(ProposedAllocation.builder().receiveItemId(1L).qty(2.0).build()))
        .orderItemInPackages(List.of(OrderItemInPackage.builder().packageNumber(1).quantity(2.0).build()))
        .build();

    return FwcOrderResponse.builder()
        .readOnly(readOnly)
        .referenceNum(referenceNum)
        .description("Order for " + referenceNum)
        .poNum("PO-7788")
        .externalId("EXT-12345")
        .earliestShipDate("2016-12-25T23:00:00")
        .shipCancelDate("2016-12-25T23:00:00")
        .notes("str")
        .numUnits1(1.0)
        .unit1Identifier(Identifier.builder().name("str").id(2L).build())
        .numUnits2(1.0)
        .unit2Identifier(Identifier.builder().name("str").id(2L).build())
        .totalWeight(1.0)
        .totalVolume(1.0)
        .billingCode("str")
        .asnNumber("str")
        .upsServiceOptionCharge(1.0)
        .upsTransportationCharge(1.0)
        .addFreightToCod(true)
        .upsIsResidential(true)
        .exportChannelIdentifier(Identifier.builder().name("str").id(2L).build())
        .routePickupDate("2016-12-25T23:00:00")
        .shippingNotes("str")
        .masterBillOfLadingId("str")
        .invoiceNumber("str")
        .fulfillInvInfo(FulfillInvInfo.builder()
            .fulfillInvShippingAndHandling(1.0)
            .fulfillInvTax(1.0)
            .fulfillInvDiscountCode("str")
            .fulfillInvDiscountAmount(1.0)
            .fulfillInvGiftMessage("str")
            .build())
        .routingInfo(RoutingInfo.builder()
            .isCod(true)
            .isInsurance(true)
            .requiresDeliveryConf(true)
            .requiresReturnReceipt(true)
            .scacCode("str")
            .carrier("str")
            .mode("str")
            .account("str")
            .shipPointZip("str")
            .capacityTypeIdentifier(Identifier.builder().name("str").id(2L).build())
            .loadNumber("str")
            .billOfLading("str")
            .trackingNumber("str")
            .trailerNumber("str")
            .sealNumber("str")
            .doorNumber("str")
            .pickupDate("2016-12-25T23:00:00")
            .build())
        .billing(Billing.builder()
            .billingCharges(List.of(BillingCharge.builder()
                .chargeType(1)
                .subtotal(1.0)
                .details(List.of(ChargeDetail.builder()
                    .warehouseTransactionPriceCalcId(1L)
                    .numUnits(2.0)
                    .chargeLabel("str")
                    .unitDescription("str")
                    .chargePerUnit(5.0)
                    .glAcctNum("str")
                    .sku("str")
                    .ptItem("str")
                    .ptItemDescription("str")
                    .ptArAcct("str")
                    .systemGenerated(true)
                    .build()))
                .build()))
            .build())
        .shipTo(shipTo)
        .soldTo(shipTo)
        .billTo(shipTo)
        .savedElements(List.of(SavedElement.builder().name("str").value("str").build()))
        .parcelOption(ParcelOption.builder()
            .orderId(1L)
            .deliveryConfirmationType("str")
            .deliveredDutyPaid(3)
            .dryIceWeight(4.0)
            .insuranceAmount(5.0)
            .insuranceType(6)
            .internationalContentsType("str")
            .internationalNonDelivery("str")
            .residentialFlag(true)
            .saturdayDeliveryFlag(true)
            .build())
        .embedded(OrderEmbeddedItems.builder()
            .items(List.of(orderItem))
            .build())
        .build();
  }

  public FwcOrderQueryResponse generateDummyOrderQueryResponse(String referenceNum) {
    return FwcOrderQueryResponse.builder()
        .totalResults(1)
        .embedded(FwcOrderQueryResponse.EmbeddedOrders.builder()
            .orders(List.of(generateDummyOrderResponse(referenceNum)))
            .build())
        .build();
  }
}
